name: GitHub Actions
on:
  push:
    branchs:
      - dev
jobs:
  setup-env:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out dev repository code
        uses: actions/checkout@dev
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workfl:o ${{ workspace }} is now ready to test your code on the runner."
    - name: Install Qt
      - run: echo "start install Qt..."
      uses: jurplel/install-qt-action@v3
      - run: echo "end install Qt..."
    - name: Install Rust
      - run: echo "start install Rust..."
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2022-06-10
            override: true
      - run: echo "end install Rust..."
  build-app:
    name: build
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
      - run: echo "start building..."
        uses: actions-rs/cargo@v1
        with:
          command: build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: echo "end building..."
