name: GitHub Actions Demo
on: [push]
jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start install Qt..."
      - run: sudo apt install python3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          setup-python: false
          modules: 'qtcharts'
      - run: echo "end install Qt..."

      - run: echo "start install Rust..."
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2022-06-10
            override: true
      - run: echo "end install Rust..."

      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The ${{ github.workspace }} is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  build-app:
    needs: setup-env
    runs-on: ubuntu-latest
    steps:
      - run: echo "start building..."
      - name: Cargon Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: echo "end building..."
